### ISSUE TITLE
Landcover dataset to graph

### ISSUE THREAD

**Issue by sdat2** [ai4er-cdt/gtc-biodiversity#8] opened 2021-01-19 11:04 UTC

**Comment by herbiebradley** [comment] 2021-01-19 15:48
1. [Only landcover dataset on CEDA](https://catalogue.ceda.ac.uk/uuid/b382ebe6679d44b8b0e68ea4ef4b701c) - 300m resolution
2. [Copernicus global landcover dataset](https://land.copernicus.eu/global/products/lc) - 100m resolution, available GEE
3. [Copernicus European landcover dataset](https://land.copernicus.eu/pan-european/corine-land-cover) - 20m resolution, direct download.
4. [UK landcover dataset](https://www.ceh.ac.uk/services/lcm2019-lcm2018-and-lcm2017) - 20m resolution, need to request access to data

All datasets appear to use GeoTiff format, so recommend we start with 1. since it's on CEDA. Then we can write some preliminary code to make a graph from the data for the Cambridge area as a first test, before scaling up or moving to one of the other datasets.

**Comment by Croydon-Brixton** [comment] 2021-02-18 14:17
Duplicate of #18 . Further discussion in #18 .

**Closed by Croydon-Brixton** 2021-02-18 14:17 UTC
Labels: action: duplicate, concerns: model, kind: feature
